name: Build release

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Check cache
      - name: Docker images cache
        id: docker-image-cache
        uses: ScribeMD/docker-cache@0.3.6
        with:
          key: ${{ runner.os }}-cache

      # Download docker images if not cached
      - name: Download docker images
        if: steps.docker-image-cache.outputs.cache-hit != 'true'
        run: |
          docker pull fbelavenuto/8bitcompilers
          docker pull fbelavenuto/xilinxise

      # Build files
      - name: Build files
        id: build
        run: |
          source driver/VERSION.INC
          echo "DRV_VERSION=${VER_MAIN}.${VER_SEC}.${VER_REV}" >> $GITHUB_OUTPUT
          NXT_VERSION=`<Nextor/VERSION`
          echo "NXT_VERSION=${NXT_VERSION}" >> $GITHUB_OUTPUT
          echo Building Driver
          docker run --rm -it -v $PWD/driver:/src fbelavenuto/8bitcompilers N80 DRIVER.ASM DRIVER.BIN
          echo Building ROM
          docker run --rm -it -v $PWD:/src fbelavenuto/8bitcompilers mknexrom Nextor/Nextor-${NXT_VERSION}.base.dat driver/SDMAPPER.ROM /d:driver/DRIVER.BIN /m:Nextor/Mapper.ASCII16.bin
          echo Building Updater
          docker run --rm -it -v $PWD/updater:/src fbelavenuto/8bitcompilers N80 SDMUPD.ASM SDMUPD.COM
          echo Building CPLD bitstream
          docker run --rm -it -v $PWD/CPLD:/workdir fbelavenuto/xilinxise make
        
      # Pack files
      - name: Pack
        shell: bash
        run: |
          tar czvf SDMapper_${{ steps.build.outputs.DRV_VERSION }}_Nextor_${{ steps.build.outputs.NXT_VERSION }}.tar.gz \
            driver/SDMAPPER.ROM CPLD/sdmapper.jed Nextor/sysfiles/*

      # Upload artifact
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Images
          path: |
            SDMapper_${{ steps.build.outputs.DRV_VERSION }}_Nextor_${{ steps.build.outputs.NXT_VERSION }}.tar.gz
          retention-days: 5

      # Publish a release if is a tag
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            driver/SDMAPPER.ROM
            CPLD/sdmapper.jed
            Nextor/sysfiles/*
